import { FieldConfig } from "@/features/room/types";
import { RoomDTO } from "@/features/room/DTO";

export const roomField: FieldConfig[] = [
  {
    name: "name",
    label: "Room Name",
    type: "text",
    width: "Full",
    maxLength: 25,
  },
  {
    name: "bedroom",
    label: "How many bedroom?",
    type: "number",
    width: "Half",
  },
  {
    name: "cr",
    label: "How many bathroom?",
    type: "number",
    width: "Half",
  },
  {
    name: "adult",
    label: "Adult Capacity",
    type: "number",
    width: "Half",
  },
  {
    name: "child",
    label: "Children Capacity",
    type: "number",
    width: "Half",
  },
  {
    name: "price",
    label: "Original Price",
    type: "amount",
    width: "Half",
  },
  {
    name: "discount",
    label: "Discount Percentage",
    type: "percentage",
    width: "Half",
  },
  {
    name: "discount_from",
    label: "Discount Start",
    type: "date",
    width: "Half",
  },
  {
    name: "discount_to",
    label: "Discount End",
    type: "date",
    width: "Half",
  },
  {
    name: "status",
    label: "Status",
    type: "select",
    width: "Full",
    options: [
      { label: "Available", value: "available" },
      { label: "Not Available", value: "not available" },
    ],
  },
  {
    name: "details",
    label: "More Details",
    type: "richText",
    width: "Full",
    placeholder: "ex: with free wifi, with breakfast",
  },
];

export const defaultValue: RoomDTO = {
  id: "",
  name: "",
  price: 0,
  status: "Available",
  discount: 0,
  details: "",
  bedroom: 1,
  cr: 0,
  adult: 1,
  child: 0,
  discount_from: undefined,
  discount_to: undefined,
};

export const sampleData = [
  {
    id: "1",
    name: "Room 1",
    price: 100,
    status: "Available",
    discount: 10,
    details: "Sea view",
    bedroom: 1,
    cr: 1,
    adult: 2,
    child: 1,
    discount_from: "2026-02-01",
    discount_to: "2026-02-10",
  },
  {
    id: "2",
    name: "Room 2",
    price: 120,
    status: "Not Available",
    discount: 15,
    details: "Garden view",
    bedroom: 1,
    cr: 1,
    adult: 2,
    child: 0,
    discount_from: "2026-02-05",
    discount_to: "2026-02-12",
  },
  {
    id: "3",
    name: "Room 3",
    price: 150,
    status: "Available",
    discount: 0,
    details: "Balcony included",
    bedroom: 2,
    cr: 1,
    adult: 3,
    child: 1,
    discount_from: undefined,
    discount_to: undefined,
  },
  {
    id: "4",
    name: "Room 4",
    price: 200,
    status: "Available",
    discount: 20,
    details: "Suite with sea view",
    bedroom: 2,
    cr: 2,
    adult: 4,
    child: 2,
    discount_from: "2026-02-10",
    discount_to: "2026-02-20",
  },
  {
    id: "5",
    name: "Room 5",
    price: 90,
    status: "Not Available",
    discount: 5,
    details: "Cozy room",
    bedroom: 1,
    cr: 1,
    adult: 1,
    child: 0,
    discount_from: "2026-02-01",
    discount_to: "2026-02-05",
  },
  {
    id: "6",
    name: "Room 6",
    price: 180,
    status: "Available",
    discount: 0,
    details: "Luxury room",
    bedroom: 2,
    cr: 2,
    adult: 3,
    child: 1,
    discount_from: undefined,
    discount_to: undefined,
  },
  {
    id: "7",
    name: "Room 7",
    price: 130,
    status: "Not Available",
    discount: 10,
    details: "Mountain view",
    bedroom: 1,
    cr: 1,
    adult: 2,
    child: 1,
    discount_from: "2026-02-02",
    discount_to: "2026-02-08",
  },
  {
    id: "8",
    name: "Room 8",
    price: 160,
    status: "Available",
    discount: 15,
    details: "City view",
    bedroom: 2,
    cr: 1,
    adult: 2,
    child: 1,
    discount_from: "2026-02-03",
    discount_to: "2026-02-10",
  },
  {
    id: "9",
    name: "Room 9",
    price: 110,
    status: "Available",
    discount: 0,
    details: "Standard room",
    bedroom: 1,
    cr: 1,
    adult: 1,
    child: 0,
    discount_from: undefined,
    discount_to: undefined,
  },
  {
    id: "10",
    name: "Room 10",
    price: 190,
    status: "Not Available",
    discount: 20,
    details: "Executive suite",
    bedroom: 2,
    cr: 2,
    adult: 4,
    child: 2,
    discount_from: "2026-02-08",
    discount_to: "2026-02-18",
  },
  {
    id: "11",
    name: "Room 11",
    price: 95,
    status: "Available",
    discount: 5,
    details: "Cozy corner",
    bedroom: 1,
    cr: 1,
    adult: 1,
    child: 0,
    discount_from: "2026-02-01",
    discount_to: "2026-02-04",
  },
  {
    id: "12",
    name: "Room 12",
    price: 170,
    status: "Not Available",
    discount: 0,
    details: "Spacious room",
    bedroom: 2,
    cr: 2,
    adult: 3,
    child: 1,
    discount_from: undefined,
    discount_to: undefined,
  },
  {
    id: "13",
    name: "Room 13",
    price: 140,
    status: "Available",
    discount: 10,
    details: "Pool view",
    bedroom: 1,
    cr: 1,
    adult: 2,
    child: 1,
    discount_from: "2026-02-06",
    discount_to: "2026-02-12",
  },
  {
    id: "14",
    name: "Room 14",
    price: 155,
    status: "Not Available",
    discount: 15,
    details: "Garden view",
    bedroom: 2,
    cr: 1,
    adult: 2,
    child: 1,
    discount_from: "2026-02-07",
    discount_to: "2026-02-14",
  },
  {
    id: "15",
    name: "Room 15",
    price: 125,
    status: "Available",
    discount: 0,
    details: "Standard room",
    bedroom: 1,
    cr: 1,
    adult: 2,
    child: 0,
    discount_from: undefined,
    discount_to: undefined,
  },
  {
    id: "16",
    name: "Room 16",
    price: 185,
    status: "Available",
    discount: 20,
    details: "Luxury suite",
    bedroom: 2,
    cr: 2,
    adult: 3,
    child: 2,
    discount_from: "2026-02-10",
    discount_to: "2026-02-20",
  },
  {
    id: "17",
    name: "Room 17",
    price: 100,
    status: "Not Available",
    discount: 5,
    details: "Comfortable room",
    bedroom: 1,
    cr: 1,
    adult: 1,
    child: 0,
    discount_from: "2026-02-01",
    discount_to: "2026-02-05",
  },
  {
    id: "18",
    name: "Room 18",
    price: 175,
    status: "Available",
    discount: 0,
    details: "Spacious suite",
    bedroom: 2,
    cr: 2,
    adult: 3,
    child: 1,
    discount_from: undefined,
    discount_to: undefined,
  },
  {
    id: "19",
    name: "Room 19",
    price: 135,
    status: "Available",
    discount: 10,
    details: "Mountain view",
    bedroom: 1,
    cr: 1,
    adult: 2,
    child: 1,
    discount_from: "2026-02-03",
    discount_to: "2026-02-09",
  },
  {
    id: "20",
    name: "Room 20",
    price: 165,
    status: "Not Available",
    discount: 15,
    details: "City view",
    bedroom: 2,
    cr: 1,
    adult: 2,
    child: 1,
    discount_from: "2026-02-04",
    discount_to: "2026-02-11",
  },
  {
    id: "21",
    name: "Room 21",
    price: 115,
    status: "Available",
    discount: 0,
    details: "Standard room",
    bedroom: 1,
    cr: 1,
    adult: 1,
    child: 0,
    discount_from: undefined,
    discount_to: undefined,
  },
  {
    id: "22",
    name: "Room 22",
    price: 195,
    status: "Available",
    discount: 20,
    details: "Executive suite",
    bedroom: 2,
    cr: 2,
    adult: 4,
    child: 2,
    discount_from: "2026-02-09",
    discount_to: "2026-02-19",
  },
  {
    id: "23",
    name: "Room 23",
    price: 105,
    status: "Not Available",
    discount: 5,
    details: "Cozy room",
    bedroom: 1,
    cr: 1,
    adult: 1,
    child: 0,
    discount_from: "2026-02-02",
    discount_to: "2026-02-07",
  },
  {
    id: "24",
    name: "Room 24",
    price: 175,
    status: "Available",
    discount: 10,
    details: "Luxury room",
    bedroom: 2,
    cr: 2,
    adult: 3,
    child: 1,
    discount_from: "2026-02-05",
    discount_to: "2026-02-15",
  },
  {
    id: "25",
    name: "Room 25",
    price: 130,
    status: "Not Available",
    discount: 0,
    details: "Mountain view",
    bedroom: 1,
    cr: 1,
    adult: 2,
    child: 1,
    discount_from: undefined,
    discount_to: undefined,
  },
  {
    id: "26",
    name: "Room 26",
    price: 160,
    status: "Available",
    discount: 15,
    details: "City view",
    bedroom: 2,
    cr: 1,
    adult: 2,
    child: 1,
    discount_from: "2026-02-06",
    discount_to: "2026-02-12",
  },
  {
    id: "27",
    name: "Room 27",
    price: 115,
    status: "Available",
    discount: 0,
    details: "Standard room",
    bedroom: 1,
    cr: 1,
    adult: 1,
    child: 0,
    discount_from: undefined,
    discount_to: undefined,
  },
  {
    id: "28",
    name: "Room 28",
    price: 190,
    status: "Not Available",
    discount: 20,
    details: "Executive suite",
    bedroom: 2,
    cr: 2,
    adult: 4,
    child: 2,
    discount_from: "2026-02-08",
    discount_to: "2026-02-18",
  },
  {
    id: "29",
    name: "Room 29",
    price: 95,
    status: "Available",
    discount: 5,
    details: "Cozy corner",
    bedroom: 1,
    cr: 1,
    adult: 1,
    child: 0,
    discount_from: "2026-02-01",
    discount_to: "2026-02-04",
  },
  {
    id: "30",
    name: "Room 30",
    price: 170,
    status: "Not Available",
    discount: 0,
    details: "Spacious room",
    bedroom: 2,
    cr: 2,
    adult: 3,
    child: 1,
    discount_from: undefined,
    discount_to: undefined,
  },
];
